### ISSUE TITLE
Error seeding BackendSeeder

### ISSUE THREAD

**Issue by bsesic** [darryldecode/laravelbackend#3]
I get an error every time I execute:
php artisan db:seed --class=BackendSeeder

This is the error.
[ReflectionException]
  Class BackendSeeder does not exist

Could I be missing a database?
I tried to migrate all the databases everything is fine there.

I have the class BackendSeeder under:
\database\seeds\BackendSeeder.php

**Comment by darryldecode** [comment]
Hello @bsesic ,

On the installation docs, on STEP 3, there is a note there to do `composer dump-autoload`

Please try that command and try to do `php artisan db:seed --class=BackendSeeder`
then let me know if it works. Thanks!

**Comment by bsesic** [comment]
I am always getting this error:
  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '[database].users' doesn't exist (SQL: insert into `users` (`first_
  name`, `last_name`, `email`, `password`, `permissions`, `updated_at`, `created_at`) values (John, Doe, admin@gmail.com, y
  a:1:{s:9:"superuser";i:1;}M2kBMxsXyo8KPIgf/efnOqJjmPEhZZthWccsszqnaXvXttA367Vi, 2015-10-22 07:54:03, 2015-10-22 07:54:03,
   ?))
[PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '[database].users' doesn't exist

**Comment by darryldecode** [comment]
That error means the user table does not exist yet so when you seed it, it throws that error..
You should do `php artisan migrate` first and when it is successful, then you can do `php artisan db:seed --class=BackendSeeder` ...

Please strictly follow the installation guide so you won't get any installation errors..

**Comment by bsesic** [comment]
Somehow `php artisan migrate` does not create the users table.
And if I do `php artisan migrate:reset`the password_resets tables is being recreated automatically.

**Comment by bsesic** [comment]
I fixed the issue with the password_resets table with `Schema::dropIfExists('password_resets');` so far.

**Comment by bsesic** [comment]
I fixed the error. You need to rename the Migration file to something like: `2014_10_12_100000_create_users_table.php` and it works.

**Comment by reypm** [comment]
Hi @darryldecode I am running the same issue as @bsesic and I have followed each step on the install docs as follow:

```
# scl enable php70 "composer update"
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.2.1)
    Loading from cache

  - Installing intervention/image (2.3.2)
    Downloading: 100%

  - Installing illuminate/html (v5.0.0)
    Downloading: 100%

  - Installing darryldecode/laravelbackend (1.0.27)
    Downloading: 100%

intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader

# scl enable php70 "php70 artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider""
Nothing to publish for tag [].

# scl enable php70 "composer dump-autoload"
Generating autoload files

# scl enable php70 "php70 artisan migrate"
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table

# scl enable php70 "php70 artisan db:seed --class=BackendSeeder"
  [ReflectionException]
  Class BackendSeeder does not exist
```

But I still getting the same issue, below is the logs:

```
[2015-11-18 12:41:56] local.ERROR: ReflectionException: Class BackendSeeder does not exist in /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Container/Container.php:737
Stack trace:
#0 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Container/Container.php(737): ReflectionClass->__construct('BackendSeeder')
#1 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build('BackendSeeder', Array)
#2 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('BackendSeeder', Array)
#3 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(71): Illuminate\Foundation\Application->make('BackendSeeder')
#4 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(61): Illuminate\Database\Console\Seeds\SeedCommand->getSeeder()
#5 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#6 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Container/Container.php(503): call_user_func_array(Array, Array)
#7 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#8 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput$
#10 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfon$
#12 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /opt/rh/httpd24/root/var/www/html/platform-cm/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Consol$
#14 /opt/rh/httpd24/root/var/www/html/platform-cm/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}
```

Any advice or help on this?

When I try to access to login (`/backend/login`) I got this issue instead:

```
NotFoundHttpException in RouteCollection.php line 161:
```

Do I miss define some routes? Or this issue is because the one above?

**Comment by darryldecode** [comment]
Hello @paquitodev,

please try:

```
php artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider" --force
```

Then:

```
composer dump-autoload
```

Then:

```
php artisan migrate
php artisan db:seed --class=BackendSeeder
```

And let me know the result. Please make sure to delete all migrations first bundled by laravel.. Thanks!

**Comment by reypm** [comment]
@darryldecode  same result as before:

```
[root@ws platform-cm-1]# scl enable php70 "php70 artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider" --force"
Nothing to publish for tag [].
[root@ws platform-cm-1]# scl enable php70 "composer dump-autoload"
Generating autoload files
[root@ws platform-cm-1]# scl enable php70 "artisan migrate"
/var/tmp/sclxj2tmY: line 8: artisan: command not found
[root@ws platform-cm-1]# scl enable php70 "php70 artisan migrate"
Nothing to migrate.
[root@ws platform-cm-1]# scl enable php70 "php70 artisan db:seed --class=BackendSeeder"

  [ReflectionException]
  Class BackendSeeder does not exist
```

**Comment by darryldecode** [comment]
looks like the vendor:publish is not publishing those needed files.

In your `config/app.php` did you already add this lines?

```
Darryldecode\Backend\BackendServiceProvider::class,
Darryldecode\Backend\BackendRoutesServiceProvider::class,
```

Also, please check your public folder if there is a folder named `backend`
and also in `database/seeds` folder, there should be a file `BackendSeeder.php`

**Comment by reypm** [comment]
- The following lines exists at `config/app.php`    
  
  ```
  Darryldecode\Backend\BackendServiceProvider::class,
  Darryldecode\Backend\BackendRoutesServiceProvider::class,
  ```
- There is not `backend` folder under `public`
- There is a `BackendSeeder.php` file under `database/seeds` folder

**Comment by darryldecode** [comment]
That is weird. When you do the vendor:publish portion, it should result like this:

```
php artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider"
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Public\backend\cb] To [\public\darryldecode\backend\cb]
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Public\backend\vendor] To [\public\darryldecode\backend\vendor]
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Config] To [\config\backend]
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Database\Migrations] To [\database\migrations]
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Database\Seeders] To [\database\seeds]
Copied Directory [\vendor\darryldecode\laravelbackend\src\Darryldecode\Backend\Components\Auth\Views] To [\resources\views\backend\auth]
Publishing complete for tag []!
```

And have those needed files copied to your application. I have tried this now and is working fine with my Linux Box and windows platform. Can you try a fresh installation of laravel again and let me know if you're still having a problem.

**Comment by reypm** [comment]
Sure, same result, see details below:

```
[root@ws platform-cm-lv]# scl enable php70 "composer update "darryldecode/laravelbackend""
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.2.1)
    Loading from cache

  - Installing intervention/image (2.3.2)
    Loading from cache

  - Installing illuminate/html (v5.0.0)
    Loading from cache

  - Installing darryldecode/laravelbackend (1.0.27)
    Loading from cache

intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
[root@ws platform-cm-lv]# scl enable php70 "php70 artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider""
Nothing to publish for tag [].
[root@ws platform-cm-lv]# scl enable php56 "php56 artisan vendor:publish --provider="Darryldecode\Backend\BackendServiceProvider""
Nothing to publish for tag [].
[root@ws platform-cm-lv]# scl enable php56 "composer dump-autoload"
Generating autoload files
[root@ws platform-cm-lv]# scl enable php56 "php56 artisan migrate"
Nothing to migrate.
[root@ws platform-cm-lv]# scl enable php56 "php56 artisan db:seed --class=BackendSeeder"
  [ReflectionException]
  Class BackendSeeder does not exist
```

I'm using PHP as SCL and I have php56 and php70 (notice in the commands) could this be a problem?

**Comment by darryldecode** [comment]
I am not sure about SCL but I guess that could possibly be the problem. Have you tried it in your local machine first?

**Comment by reypm** [comment]
That's my local environment a CentOS server running PHP as SCL (Software Collection)

**Comment by darryldecode** [comment]
Looks like the `vendor:publish` portion fails to do its job. I haven't tested this with PHP as SCL. Do you have any other environment that you could try aside from that SCL?

**Comment by reypm** [comment]
@darryldecode I will clone a clean env and will install only one Apache/PHP and will try, will be back as soon as I test with some feedback

**Comment by remicollet** [comment]
> I am not sure about SCL but I guess that could possibly be the problem. Have you tried it in your local machine first?

I really don't think  SCL can create issue, once enable, PATH is adapted to the right installation tree, as most of developers  do on their system when working with multiple versions.

**Comment by bsesic** [comment]
Closed due to inactivity.
